#!python3
"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over
five hundred divisors?
"""

import logging, time

logging.basicConfig(level=logging.DEBUG,
                    format="[%(levelname)s] %(message)s")


def triangle_numbers(start):
    natural = 0
    triangle = 0
    while triangle < start:
        natural += 1
        triangle += natural
    while True:
        yield triangle
        natural += 1
        triangle += natural


def solve(targetDivisors):
    for n in triangle_numbers(targetDivisors):
        logging.debug("Trying triangle " + str(n))
        divisorsCounted = 0
        minDivisor = 1
        maxDivisor = n
        
        for divisor in range(1, n+1):
            if n % divisor == 0:
                minDivisor = divisor
                maxDivisor = n // divisor
                if minDivisor > maxDivisor:
                    break
                else:
                    divisorsCounted += 1
            
        
        if divisorsCounted*2 >= targetDivisors:
            return n


if __name__ == '__main__':
    
    # for n, i in zip(triangle_numbers(5), range(10 + 1)):
    #     if i == 10:
    #         break
    #     else:
    #         print(n)

    print()
    s = time.time()
    n = solve(5)
    e = time.time()
    t = e-s
    minutes = t // 60
    seconds = t % 60
    print("The value of the first triangle number to have over five " \
          "divisors is", n)
    print("Found in %d minutes and %f seconds." % (minutes, seconds))

    print()
    s = time.time()
    n = solve(500)
    e = time.time()
    t = e-s
    minutes = t // 60
    seconds = t % 60
    print("The value of the first triangle number to have over five hundred " \
          "divisors is", n)
    print("Found in %d minutes and %f seconds." % (minutes, seconds))
